#!/bin/sh

[ "$#" -ge 2 ] || exit 1

kind="$1"
disp="$2"
path="${3:-$disp}"
host="${4:-$SERVER_HOST}"
port="${5:-${SERVER_PORT:-70}}"

printf '%s%s\t%s\t%s\t%s\r\n' "$kind" "$disp" "$path" "$host" "$port" 2>/dev/null
