#!/bin/sh

IFS=''
while read -r line
do
	if echo "$line" | fgrep -q "	"
	then
		kind=$(echo "$line" | cut -f 1 | cut -c 1)
		disp=$(echo "$line" | cut -f 1 | cut -c 2-)
		path=$(echo "$line" | cut -f 2)
		host=$(echo "$line" | cut -f 3)
		port=$(echo "$line" | cut -f 4)

		if [ ! "$path" ]
		then
			path="$REQUEST/$disp"

			if [ -d "$disp" ] && [ -e "$disp"/gophertag ]
			then
				disp="$(cat "$disp/gophertag")"
			fi
		fi

		if [ ! "$host" ]
		then
			if [ "$SERVER_HOST" ]
			then
				host="$SERVER_HOST"
			else
				host="localhost"
			fi
		fi

		if [ ! "$port" ]
		then
			if [ "$SERVER_PORT" ]
			then
				port="$SERVER_PORT"
			else
				port="70"
			fi
		fi

		phitem "$kind" "$disp" "$path" "$host" "$port"
	else
		phinfo "$line"
	fi
done
